eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8084

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
